site_name: 3D production studio website

nav:
  - Home: index.md
  - Journal one: journalOne.md
  - Journal two: journalTwo.md
  - Journal three: journalThree.md

theme: readthedocs

markdown_extensions:
  - attr_list